[build-system]
requires = [
    "setuptools>=45", "setuptools_scm[toml]>=6.2", "babel"
]
build-backend = "setuptools.build_meta"

[project]
name = "cryptoadvance.spectrum"

authors = [
  { name="Stepan Snigirev"},
  { name="k9ert"},
]
description = "Implements A Bitcoin Core API which querying an Electrum"
urls = { Homepage = "https://github.com/cryptoadvance/spectrum" }
readme = "README.md"

requires-python = ">=3.10"

license = {file = "LICENSE"}

classifiers =[
    'Programming Language :: Python :: 3',
    'License :: OSI Approved :: MIT License',
    'Operating System :: OS Independent',
    'Framework :: Flask',
]
dynamic=["version"]

[tool.setuptools_scm]
write_to = "src/cryptoadvance/spectrum/_version.py"

[project.optional-dependencies]
test = [
  "cryptoadvance.specter>=1.14.5",
  "pytest >=7.1.3",
  "pytest-cov[all]"
]